version: '3'

services:
  mongodb:
    container_name: "noti_services_mongodb"
    image: mongo
    networks:
      - noti_network
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - mongodb:/data/db
  rabbit:
    container_name: "noti_services_rabbitmq"
    image: rabbitmq:management
    networks:
      - noti_network
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  api:
    container_name: "noti_services_api"
    build:
      context: .
      dockerfile: ./api.Dockerfile
    ports:
      - "8093:8093"
    networks:
      - noti_network
    depends_on:
      - mongodb
      - rabbit
    env_file:
      - ./.env

networks:
  noti_network:
volumes:
  mongodb:
  rabbitmq:
